### PR TITLE
Added a test to show globstar skips filepath that contains _ and . characters

### PR DESCRIPTION
**Pull request by sole6**
This issue was also created https://github.com/gflohr/File-Globstar/issues/5

### CODE REVIEW

**Review by gflohr — CHANGES_REQUESTED** [review]
Your test fails here and on Travis CI.  Have you committed everything?

I also do not really understand what you are testing here. Could you describe it a little bit more detailed?

Thanks!

**Comment by gflohr** [comment]
Okay, I had missed your bug report. I will have a look.

**Comment by sole6** [comment]
Yes, i have commited everything.
So, the test should fail :) 
Here is what i wanted to show. 
globstar does not seem to search in folders that contain "_" or "." . And that is what i wanted to show.

**Comment by gflohr** [comment]
Yes, thanks, everything is clear now.  I had missed the context.

**Pull request merged**
