### PR TITLE
Add AppVeyor CI support

### PR DESCRIPTION
**Pull request by rivy**
* adds support for [AppVeyor CI](https://ci.appveyor.com/project/rivy/perl-file-globstar) (will need short setup on your AppVeyor account)
  * testing back to perl v5.8.8
* also includes support for [CodeCov](https://codecov.io/gh/rivy/perl.File-Globstar/branches) and [Coveralls](https://coveralls.io/github/rivy/perl.File-Globstar) (optional; will need some minor extra setup on your AppVeyor account)

### CODE REVIEW

**Comment by rivy** [comment]
I have been looking to add "globstar" support to my [Win32::CommandLine](https://metacpan.org/pod/Win32::CommandLine) module. And so, I came across your module but had difficulties when downloading and exploring/testing it.

The testing problems seem all to be contained in "t/listmatch-gitignore.t", but I'm still not sure exactly what the real issues are...

So, I fixed an `@INC` problem, disabled automatic testing of "t/listmatch-gitignore.t", and added AppVeyor CI testing so that you would be able to more easily look into the issues.

The AppVeyor tests take about 3 minutes per `perl` version tested, so, if you'd like, I can reduce the versions tested. I'd suggest, at least "5.8.8", "5.12", "5.16", maybe "5.20", and latest (with code coverage).

To enable the author tests, just add "AUTHOR_TESTING" = "1" in your AppVeyor environment settings, then you'll get all the tests, but contributors won't be tripped up.

If you'd like any other changes, I'm happy to update the PR.

- Roy

**Comment by gflohr** [comment]
Thanks for the patch! At the moment I have no access to any Windows machine, so AppVeyor looks good.

The purpose of "listmatch-gitignore.t" is test that File-Globstar behaves the same as git with gitignore files.  It's okay to mark that as an author test.  I will probably add one more explicit environment variable so that the test runs again on TravisCI.  The "real" issue with the test could be that it uses Git.pm which ships with git.  The CPAN testers reports for Git.pm suggest that it doesn't work under Windows.  And I think I have also read that somewhere in the docs or in a source code comment.

I didn't understand why I need .gitattributes.  There are no .cmd or .bat files in the repository.  Or did I miss something?

What do I have to do in my AppVeyor account to enable CodeCovs and Coverall?

I hope you can use the module with Win32::CommandLine.  Let me know, if I can help.

Guido

**Comment by gflohr** [comment]
Okay, now there *is* a .bat file in the distribution.  ;) Forget the question about .gitattributes.

I can make a new release on CPAN, whenever you want.

**Comment by rivy** [comment]
For coverage, you need to define an AppVeyor environment variable containing the upload token from the desired coverage site. The environment variables are set from the "Environment" tab of the "Settings" section on the module's AppVeyor project page.

So, starting from a working AppVeyor project:

### [CodeCov](https://codecov.io) 
1. Initiate CodeCov coverage by adding the module repository
2. From the CodeCov module repository page, under "Settings / General", find the "Repository Upload Token"
3. Copy this token to the environment variable `CODECOV_TOKEN` within the module's AppVeyor project and, optionally (*recommended*), encrypt it using the lock icon (:lock:) to the right of the value entry box
4. Click SAVE

### [Coveralls](https://coveralls.io/) 
1. Initiate Codeveralls coverage by adding the module repository
2. From the Coveralls repository page, find the token in the "Token" box (top upper right)
3. Copy this token to the environment variable `COVERALLS_TOKEN` within the module's AppVeyor project and, optionally (*recommended*), encrypt it using the lock icon (:lock:) to the right of the value entry box
4. Click SAVE

The next initiation of a build/test on AppVeyor will use the tokens to upload coverage info for any build signalling a coverage request (via the `COVERAGE` variable).

**Comment by gflohr** [comment]
Thanks, I'll put that on the todo list.

**Pull request merged**
